const products = [
  {
    "hpmSku": "HPM-KM-0002",
    "kmartSku": "P_42941842",
    "name": "Sikat Bulu Pin & Bristle untuk Kucing",
    "nameOriginal": "Pet Brush Pin and Bristle",
    "categoryDisplay": "Grooming & Perawatan",
    "categorySlug": "grooming-perawatan",
    "status": "top_pick",
    "price": 75000,
    "priceDisplay": "Rp75,000",
    "productUrl": "https://www.kmart.com.au/product/pet-brush-pin-and-bristle-42941842/",
    "imageUrl": "https://assets.kmart.com.au/transform/35049b03-8017-4bd0-b752-88c78497bdc7/42941842-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "sikat bulu kucing, pet brush, brush kucing, sisir kucing, grooming brush, pin brush, bristle brush",
    "seoPrimaryKeyword": "alat grooming kucing",
    "seoSupportingKeywords": "sikat bulu kucing, brush kucing, sisir kucing, grooming kucing di rumah",
    "descriptorShort": "Sikat Bulu Pin & Bristle untuk Kucing untuk membantu grooming basic kucing di rumah, seperti merapikan bulu atau perawatan kuku."
  },
  {
    "hpmSku": "HPM-KM-0003",
    "kmartSku": "P_42442653",
    "name": "Sarung Tangan Grooming untuk Kucing",
    "nameOriginal": "Pet Grooming Mitt",
    "categoryDisplay": "Grooming & Perawatan",
    "categorySlug": "grooming-perawatan",
    "status": "top_pick",
    "price": 75000,
    "priceDisplay": "Rp75,000",
    "productUrl": "https://www.kmart.com.au/product/pet-grooming-mitt-42442653/",
    "imageUrl": "https://assets.kmart.com.au/transform/04ed16c1-8add-4cb1-a016-a7faa9ec5a97/42442653-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "sarung tangan grooming, grooming mitt, glove grooming, sikat tangan kucing, bersihin bulu, shedding glove",
    "seoPrimaryKeyword": "sarung tangan grooming kucing",
    "seoSupportingKeywords": "grooming mitt kucing, sarung tangan bulu kucing, alat bersih bulu kucing",
    "descriptorShort": "Sarung Tangan Grooming untuk Kucing untuk membantu grooming basic kucing di rumah, seperti merapikan bulu atau perawatan kuku."
  },
  {
    "hpmSku": "HPM-KM-0004",
    "kmartSku": "P_42442592",
    "name": "Gunting Kuku Kucing",
    "nameOriginal": "Pet Nail Clippers",
    "categoryDisplay": "Grooming & Perawatan",
    "categorySlug": "grooming-perawatan",
    "status": "top_pick",
    "price": 75000,
    "priceDisplay": "Rp75,000",
    "productUrl": "https://www.kmart.com.au/product/pet-nail-clippers-42442592/",
    "imageUrl": "https://assets.kmart.com.au/transform/c1fed205-5529-4fb9-a761-4ece11a39fce/42442592-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "gunting kuku kucing, nail clipper, pemotong kuku kucing, pet nail cutter, grooming kuku",
    "seoPrimaryKeyword": "gunting kuku kucing",
    "seoSupportingKeywords": "pemotong kuku kucing, nail clipper kucing, grooming kuku kucing",
    "descriptorShort": "Gunting Kuku Kucing untuk membantu grooming basic kucing di rumah, seperti merapikan bulu atau perawatan kuku."
  },
  {
    "hpmSku": "HPM-KM-0005",
    "kmartSku": "P_42941859",
    "name": "Sikat Slicker Kayu untuk Kucing",
    "nameOriginal": "Pet Brush Slicker Wooden",
    "categoryDisplay": "Grooming & Perawatan",
    "categorySlug": "grooming-perawatan",
    "status": "show",
    "price": 75000,
    "priceDisplay": "Rp75,000",
    "productUrl": "https://www.kmart.com.au/product/pet-brush-slicker-wooden-42941859/",
    "imageUrl": "https://assets.kmart.com.au/transform/6168d5ee-4c6d-4290-b74b-22fc0fe7f667/42941859-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "slicker brush, sikat bulu rontok, brush kucing, grooming brush, sisir bulu kucing, wooden brush",
    "seoPrimaryKeyword": "slicker brush kucing",
    "seoSupportingKeywords": "sikat bulu rontok kucing, sisir bulu kucing, grooming brush kucing",
    "descriptorShort": "Sikat Slicker Kayu untuk Kucing untuk membantu grooming basic kucing di rumah, seperti merapikan bulu atau perawatan kuku."
  },
  {
    "hpmSku": "HPM-KM-0006",
    "kmartSku": "P_43514182",
    "name": "Mainan Slinky Chaser untuk Kucing",
    "nameOriginal": "Cat Toy Slinky Chaser",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 75000,
    "priceDisplay": "Rp75,000",
    "productUrl": "https://www.kmart.com.au/product/cat-toy-slinky-chaser-43514182/",
    "imageUrl": "https://assets.kmart.com.au/transform/43456120-c588-424b-9ef4-f2b8f430308d/43514182-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "mainan kucing, slinky chaser, cat toy, mainan interaktif, toy chaser, enrichment kucing",
    "seoPrimaryKeyword": "mainan kucing indoor",
    "seoSupportingKeywords": "mainan interaktif kucing, cat toy, mainan chaser kucing",
    "descriptorShort": "Mainan Slinky Chaser untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0007",
    "kmartSku": "P_43511433",
    "name": "Kalung Kucing - Assorted",
    "nameOriginal": "Cat Collar - Assorted",
    "categoryDisplay": "Aksesoris & Harness",
    "categorySlug": "aksesoris-harness",
    "status": "show",
    "price": 75000,
    "priceDisplay": "Rp75,000",
    "productUrl": "https://www.kmart.com.au/product/cat-collar-assorted-43511433/",
    "imageUrl": "https://assets.kmart.com.au/transform/3e27a53c-ccf6-44d1-9659-a59dbeda7ce7/43511433-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "collar kucing, kalung kucing, cat collar, aksesoris kucing, kalung anabul",
    "seoPrimaryKeyword": "collar kucing",
    "seoSupportingKeywords": "kalung kucing, cat collar, aksesoris kucing",
    "descriptorShort": "Kalung Kucing - Assorted sebagai aksesoris atau perlengkapan jalan kucing. Pastikan ukuran pas dan nyaman dipakai."
  },
  {
    "hpmSku": "HPM-KM-0008",
    "kmartSku": "P_43408511",
    "name": "Paket 6 Mainan Tikus untuk Kucing",
    "nameOriginal": "Cat Toy Mouse 6 Pack",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 75000,
    "priceDisplay": "Rp75,000",
    "productUrl": "https://www.kmart.com.au/product/cat-toy-mouse-6-pack-43408511/",
    "imageUrl": "https://assets.kmart.com.au/transform/752f9fe1-2bd9-4889-a555-8b421a38405f/43408511-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "mainan tikus kucing, mouse toy, cat toy, paket mainan kucing, toy mouse, mainan berburu",
    "seoPrimaryKeyword": "mainan tikus kucing",
    "seoSupportingKeywords": "cat mouse toy, mainan berburu kucing, paket mainan kucing",
    "descriptorShort": "Paket 6 Mainan Tikus untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0009",
    "kmartSku": "P_43715954",
    "name": "Kalung Kucing - Assorted",
    "nameOriginal": "Cat Collar - Assorted",
    "categoryDisplay": "Aksesoris & Harness",
    "categorySlug": "aksesoris-harness",
    "status": "show",
    "price": 75000,
    "priceDisplay": "Rp75,000",
    "productUrl": "https://www.kmart.com.au/product/cat-collar-assorted-43715954/",
    "imageUrl": "https://assets.kmart.com.au/transform/dd86a95d-b76f-4a5e-85bd-1806adb38550/43715954-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "collar kucing, kalung kucing, cat collar, aksesoris kucing, kalung anabul",
    "seoPrimaryKeyword": "collar kucing",
    "seoSupportingKeywords": "kalung kucing, cat collar, aksesoris kucing",
    "descriptorShort": "Kalung Kucing - Assorted sebagai aksesoris atau perlengkapan jalan kucing. Pastikan ukuran pas dan nyaman dipakai."
  },
  {
    "hpmSku": "HPM-KM-0010",
    "kmartSku": "P_43408528",
    "name": "Paket 12 Bola Mainan untuk Kucing",
    "nameOriginal": "12 Pack Cat Toy Balls",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 137500,
    "priceDisplay": "Rp137,500",
    "productUrl": "https://www.kmart.com.au/product/12-pack-cat-toy-balls-43408528/",
    "imageUrl": "https://assets.kmart.com.au/transform/caef0212-532e-4997-b79f-55ebd1b69f99/43408528-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "bola mainan kucing, cat toy balls, mainan bola, paket mainan kucing, toy ball, enrichment kucing",
    "seoPrimaryKeyword": "bola mainan kucing",
    "seoSupportingKeywords": "cat toy balls, mainan bola kucing, paket mainan kucing",
    "descriptorShort": "Paket 12 Bola Mainan untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0011",
    "kmartSku": "P_43660094",
    "name": "Paket Mainan Kucing Sardine",
    "nameOriginal": "Cat Toy Pack Sardine",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 137500,
    "priceDisplay": "Rp137,500",
    "productUrl": "https://www.kmart.com.au/product/cat-toy-pack-sardine-43660094/",
    "imageUrl": "https://assets.kmart.com.au/transform/4ef45e14-4719-41f9-9bfa-000d22b93acd/43660094-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "mainan ikan kucing, sardine toy, cat toy, mainan catnip, mainan gigit kucing, toy fish",
    "seoPrimaryKeyword": "mainan ikan kucing",
    "seoSupportingKeywords": "mainan sardine kucing, cat toy fish, mainan gigit kucing",
    "descriptorShort": "Paket Mainan Kucing Sardine untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0012",
    "kmartSku": "P_43514533",
    "name": "2 Mainan Tikus Chaser untuk Kucing",
    "nameOriginal": "2 Pack Cat Toy Mouse Chasers",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 137500,
    "priceDisplay": "Rp137,500",
    "productUrl": "https://www.kmart.com.au/product/2-pack-cat-toy-mouse-chasers-43514533/",
    "imageUrl": "https://assets.kmart.com.au/transform/b51e76dd-ae98-4e29-aa99-ac31117d5d99/43514533-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "mouse chaser, mainan tikus kucing, cat toy, mainan berburu, toy chaser, paket mainan",
    "seoPrimaryKeyword": "mainan tikus kucing",
    "seoSupportingKeywords": "mouse chaser kucing, mainan berburu kucing, cat toy",
    "descriptorShort": "2 Mainan Tikus Chaser untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0013",
    "kmartSku": "P_43660100",
    "name": "Paket 4 Mainan Kucing",
    "nameOriginal": "Cat Toy 4 Pack",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 137500,
    "priceDisplay": "Rp137,500",
    "productUrl": "https://www.kmart.com.au/product/cat-toy-4-pack-43660100/",
    "imageUrl": "https://assets.kmart.com.au/transform/a92d8292-6eef-477b-a9d4-4674d41d3e48/43660100-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "paket mainan kucing, cat toy pack, mainan anabul, mainan interaktif, enrichment toy",
    "seoPrimaryKeyword": "paket mainan kucing",
    "seoSupportingKeywords": "cat toy pack, mainan kucing indoor, mainan enrichment kucing",
    "descriptorShort": "Paket 4 Mainan Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0014",
    "kmartSku": "P_43715206",
    "name": "Paket Mainan Teaser Plush Kucing",
    "nameOriginal": "Teaser Plush Pack - Assorted",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 137500,
    "priceDisplay": "Rp137,500",
    "productUrl": "https://www.kmart.com.au/product/teaser-plush-pack-assorted-43715206/",
    "imageUrl": "https://assets.kmart.com.au/transform/5b6ad600-11b7-49e4-9f2d-696848786389/43715206-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "teaser kucing, plush teaser, cat teaser, mainan pancing kucing, wand toy, mainan interaktif",
    "seoPrimaryKeyword": "teaser kucing",
    "seoSupportingKeywords": "mainan pancing kucing, cat teaser wand, mainan interaktif kucing",
    "descriptorShort": "Paket Mainan Teaser Plush Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0015",
    "kmartSku": "P_43715145",
    "name": "Boneka Mainan Plush untuk Kucing",
    "nameOriginal": "Cat Plush Toy - Assorted",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 137500,
    "priceDisplay": "Rp137,500",
    "productUrl": "https://www.kmart.com.au/product/cat-plush-toy-assorted-43715145/",
    "imageUrl": "https://assets.kmart.com.au/transform/1503b65c-eaa7-4f69-99bb-a6f8e24fc882/43715145-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "boneka kucing, plush toy, cat plush, mainan gigit, mainan peluk kucing, soft toy",
    "seoPrimaryKeyword": "boneka mainan kucing",
    "seoSupportingKeywords": "plush toy kucing, mainan gigit kucing, cat plush toy",
    "descriptorShort": "Boneka Mainan Plush untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0016",
    "kmartSku": "P_43715169",
    "name": "Mainan Plush Cardboard untuk Kucing",
    "nameOriginal": "Cardboard Plush Toy - Assorted",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 137500,
    "priceDisplay": "Rp137,500",
    "productUrl": "https://www.kmart.com.au/product/cardboard-plush-toy-assorted-43715169/",
    "imageUrl": "https://assets.kmart.com.au/transform/b59a83d4-0d20-4398-a23b-0afb194ecccf/43715169-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "cardboard plush toy, mainan kucing, cat toy, mainan gigit, plush kucing, enrichment toy",
    "seoPrimaryKeyword": "mainan kucing indoor",
    "seoSupportingKeywords": "cardboard plush toy, mainan gigit kucing, cat toy",
    "descriptorShort": "Mainan Plush Cardboard untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0017",
    "kmartSku": "P_43715176",
    "name": "Tongkat Teaser Kucing Multi-Mainan",
    "nameOriginal": "Multi-Teaser Wand",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 137500,
    "priceDisplay": "Rp137,500",
    "productUrl": "https://www.kmart.com.au/product/multi-teaser-wand-43715176/",
    "imageUrl": "https://assets.kmart.com.au/transform/ecdefafa-049c-4c5b-a537-c18a8f52f6f3/43715176-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "tongkat mainan kucing, teaser wand, cat wand, mainan pancing, mainan interaktif, multi teaser",
    "seoPrimaryKeyword": "tongkat mainan kucing",
    "seoSupportingKeywords": "teaser wand kucing, mainan pancing kucing, mainan interaktif",
    "descriptorShort": "Tongkat Teaser Kucing Multi-Mainan untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0018",
    "kmartSku": "P_43715190",
    "name": "Boneka Tikus Besar untuk Kucing",
    "nameOriginal": "Large Mouse Plush - Assorted",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 137500,
    "priceDisplay": "Rp137,500",
    "productUrl": "https://www.kmart.com.au/product/large-mouse-plush-assorted-43715190/",
    "imageUrl": "https://assets.kmart.com.au/transform/c7bcdadf-31a7-4881-a101-590abc251f38/43715190-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "boneka tikus, mouse plush, mainan tikus besar, cat toy, plush toy, mainan berburu",
    "seoPrimaryKeyword": "mainan tikus kucing",
    "seoSupportingKeywords": "boneka tikus kucing, mouse plush toy, mainan berburu kucing",
    "descriptorShort": "Boneka Tikus Besar untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0019",
    "kmartSku": "P_43715152",
    "name": "Mainan Tali Plush untuk Kucing",
    "nameOriginal": "Cat Rope Plush Toy - Assorted",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 137500,
    "priceDisplay": "Rp137,500",
    "productUrl": "https://www.kmart.com.au/product/cat-rope-plush-toy-assorted-43715152/",
    "imageUrl": "https://assets.kmart.com.au/transform/40eb18b3-5fd1-4ee2-bcde-64ff191a2fa5/43715152-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "rope plush toy, mainan tali kucing, cat toy, mainan gigit, plush rope, enrichment",
    "seoPrimaryKeyword": "mainan tali kucing",
    "seoSupportingKeywords": "rope plush toy kucing, mainan gigit kucing, cat toy",
    "descriptorShort": "Mainan Tali Plush untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0020",
    "kmartSku": "P_43715213",
    "name": "Mainan Teaser Party Plush untuk Kucing",
    "nameOriginal": "Teaser Party Plush - Assorted",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 137500,
    "priceDisplay": "Rp137,500",
    "productUrl": "https://www.kmart.com.au/product/teaser-party-plush-assorted-43715213/",
    "imageUrl": "https://assets.kmart.com.au/transform/9c64c7b1-d0fe-4caa-98c3-7566392430ec/43715213-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "teaser party, plush teaser, mainan pancing kucing, cat teaser, wand toy, mainan interaktif",
    "seoPrimaryKeyword": "teaser kucing",
    "seoSupportingKeywords": "mainan pancing kucing, plush teaser, mainan interaktif kucing",
    "descriptorShort": "Mainan Teaser Party Plush untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0021",
    "kmartSku": "P_43715183",
    "name": "Boneka Plush Novelty Besar untuk Kucing",
    "nameOriginal": "Large Novelty Plush - Assorted",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 137500,
    "priceDisplay": "Rp137,500",
    "productUrl": "https://www.kmart.com.au/product/large-novelty-plush-assorted-43715183/",
    "imageUrl": "https://assets.kmart.com.au/transform/da810550-18b8-4744-b216-d7a84f2d2bd9/43715183-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "novelty plush, boneka kucing, cat plush toy, mainan lucu kucing, plush besar, mainan gigit",
    "seoPrimaryKeyword": "boneka mainan kucing",
    "seoSupportingKeywords": "novelty plush kucing, mainan lucu kucing, cat plush toy",
    "descriptorShort": "Boneka Plush Novelty Besar untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0022",
    "kmartSku": "P_43510290",
    "name": "Pelindung Furnitur untuk Hewan",
    "nameOriginal": "Pet Furniture Protector",
    "categoryDisplay": "Rumah & Proteksi",
    "categorySlug": "rumah-proteksi",
    "status": "show",
    "price": 175000,
    "priceDisplay": "Rp175,000",
    "productUrl": "https://www.kmart.com.au/product/pet-furniture-protector-43510290/",
    "imageUrl": "https://assets.kmart.com.au/transform/f11817a4-e5ef-47d8-b81f-f2cda7375f41/43510290-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "pelindung furniture, sofa protector, pet furniture protector, anti cakaran, pelindung sofa, proteksi rumah",
    "seoPrimaryKeyword": "pelindung sofa dari cakaran kucing",
    "seoSupportingKeywords": "furniture protector pet, anti cakaran kucing, pelindung furniture",
    "descriptorShort": "Pelindung Furnitur untuk Hewan untuk membantu melindungi furnitur/area rumah dari bulu atau cakaran anabul."
  },
  {
    "hpmSku": "HPM-KM-0023",
    "kmartSku": "P_43717705",
    "name": "Ruffle Bag Mainan Kucing",
    "nameOriginal": "Cat Ruffle Bag - Assorted",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 175000,
    "priceDisplay": "Rp175,000",
    "productUrl": "https://www.kmart.com.au/product/cat-ruffle-bag-assorted-43717705/",
    "imageUrl": "https://assets.kmart.com.au/transform/0804f428-32b2-444a-931e-21e147317cc6/43717705-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "ruffle bag, mainan kantong kucing, cat toy bag, mainan interaktif, enrichment, mainan sembunyi",
    "seoPrimaryKeyword": "mainan enrichment kucing",
    "seoSupportingKeywords": "ruffle bag kucing, mainan sembunyi kucing, cat enrichment toy",
    "descriptorShort": "Ruffle Bag Mainan Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0024",
    "kmartSku": "P_43408306",
    "name": "Tongkat Multi Teaser untuk Kucing",
    "nameOriginal": "Cat Toy Multi Teaser Wand",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 187500,
    "priceDisplay": "Rp187,500",
    "productUrl": "https://www.kmart.com.au/product/cat-toy-multi-teaser-wand-43408306/",
    "imageUrl": "https://assets.kmart.com.au/transform/7167fb7e-b1fa-46ed-af12-117def521358/43408306-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "multi teaser, tongkat mainan kucing, cat wand, teaser wand, mainan pancing, interactive toy",
    "seoPrimaryKeyword": "tongkat mainan kucing",
    "seoSupportingKeywords": "multi teaser kucing, cat wand, mainan pancing kucing",
    "descriptorShort": "Tongkat Multi Teaser untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0025",
    "kmartSku": "P_43674817",
    "name": "Boneka Kura-Kura Catnip untuk Kucing",
    "nameOriginal": "Turtle with Catnip",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "top_pick",
    "price": 187500,
    "priceDisplay": "Rp187,500",
    "productUrl": "https://www.kmart.com.au/product/turtle-with-catnip-43674817/",
    "imageUrl": "https://assets.kmart.com.au/transform/d12e09a0-cd6e-461d-a9c7-14177ab60922/43674817-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "catnip toy, mainan catnip, turtle toy, boneka kucing, mainan gigit, enrichment kucing",
    "seoPrimaryKeyword": "mainan catnip kucing",
    "seoSupportingKeywords": "catnip toy, boneka catnip kucing, mainan gigit kucing",
    "descriptorShort": "Boneka Kura-Kura Catnip untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0026",
    "kmartSku": "P_43674770",
    "name": "2 Boneka Ikan Kecil Catnip untuk Kucing",
    "nameOriginal": "2 Pack Little Fish Catnip",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 187500,
    "priceDisplay": "Rp187,500",
    "productUrl": "https://www.kmart.com.au/product/2-pack-little-fish-catnip-43674770/",
    "imageUrl": "https://assets.kmart.com.au/transform/d8e947c5-03af-4c89-a12c-066adc07e3ca/43674770-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "catnip fish, mainan ikan kucing, catnip toy, toy fish, mainan gigit, enrichment",
    "seoPrimaryKeyword": "mainan catnip kucing",
    "seoSupportingKeywords": "catnip fish toy, mainan ikan kucing, boneka catnip",
    "descriptorShort": "2 Boneka Ikan Kecil Catnip untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0027",
    "kmartSku": "P_43674787",
    "name": "Boneka Beaver Catnip untuk Kucing",
    "nameOriginal": "Beaver with Catnip",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 187500,
    "priceDisplay": "Rp187,500",
    "productUrl": "https://www.kmart.com.au/product/beaver-with-catnip-43674787/",
    "imageUrl": "https://assets.kmart.com.au/transform/f1b1579c-ec9f-478d-b8e1-a3dc54f79ffa/43674787-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "beaver catnip, catnip toy, boneka catnip, mainan kucing, mainan gigit, enrichment",
    "seoPrimaryKeyword": "mainan catnip kucing",
    "seoSupportingKeywords": "boneka catnip, catnip toy kucing, mainan gigit kucing",
    "descriptorShort": "Boneka Beaver Catnip untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0028",
    "kmartSku": "P_43674824",
    "name": "Boneka Siput Catnip untuk Kucing",
    "nameOriginal": "Snail with Catnip",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 187500,
    "priceDisplay": "Rp187,500",
    "productUrl": "https://www.kmart.com.au/product/snail-with-catnip-43674824/",
    "imageUrl": "https://assets.kmart.com.au/transform/c7cd4cd9-e845-43a7-b187-3309822539b6/43674824-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "snail catnip, catnip toy, boneka siput, mainan kucing, mainan gigit, enrichment",
    "seoPrimaryKeyword": "mainan catnip kucing",
    "seoSupportingKeywords": "snail catnip toy, boneka catnip kucing, mainan kucing indoor",
    "descriptorShort": "Boneka Siput Catnip untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0029",
    "kmartSku": "P_43674800",
    "name": "Boneka Beruang Catnip untuk Kucing",
    "nameOriginal": "Bear with Catnip",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 187500,
    "priceDisplay": "Rp187,500",
    "productUrl": "https://www.kmart.com.au/product/bear-with-catnip-43674800/",
    "imageUrl": "https://assets.kmart.com.au/transform/7be23b1e-996a-4528-bf5d-0d094cdfa10a/43674800-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "bear catnip, catnip toy, boneka beruang, mainan kucing, mainan gigit, enrichment",
    "seoPrimaryKeyword": "mainan catnip kucing",
    "seoSupportingKeywords": "bear catnip toy, boneka catnip kucing, mainan gigit kucing",
    "descriptorShort": "Boneka Beruang Catnip untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0030",
    "kmartSku": "P_43659180",
    "name": "Cave Anak Kucing",
    "nameOriginal": "Cat Kitten Cave",
    "categoryDisplay": "Kasur & Tempat Tidur",
    "categorySlug": "kasur-tempat-tidur",
    "status": "top_pick",
    "price": 225000,
    "priceDisplay": "Rp225,000",
    "productUrl": "https://www.kmart.com.au/product/cat-kitten-cave-43659180/",
    "imageUrl: "assets/products/HPM-KM-0002.jpg",
    "searchKeywords": "cat cave, rumah kucing, tempat tidur kucing, kitten cave, kasur kucing, hideout kucing",
    "seoPrimaryKeyword": "rumah kucing",
    "seoSupportingKeywords": "cat cave, tempat tidur kucing, kasur kucing, hideout kucing",
    "descriptorShort": "Cave Anak Kucing sebagai area istirahat atau hideout kucing, cocok untuk anabul yang suka tempat tidur tertutup/nyaman."
  },
  {
    "hpmSku": "HPM-KM-0031",
    "kmartSku": "P_43659289",
    "name": "Tempat Tidur Teddy Cave untuk Kucing",
    "nameOriginal": "Cat Teddy Cave",
    "categoryDisplay": "Kasur & Tempat Tidur",
    "categorySlug": "kasur-tempat-tidur",
    "status": "top_pick",
    "price": 225000,
    "priceDisplay": "Rp225,000",
    "productUrl": "https://www.kmart.com.au/product/cat-teddy-cave-43659289/",
    "imageUrl": "https://assets.kmart.com.au/transform/e5a48467-97ba-4b1f-bd6c-dedd3643987e/43659289-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "teddy cave, cat cave, rumah kucing, tempat tidur kucing, kasur kucing, hideout",
    "seoPrimaryKeyword": "rumah kucing",
    "seoSupportingKeywords": "cat cave, tempat tidur kucing, teddy cave, kasur kucing",
    "descriptorShort": "Tempat Tidur Teddy Cave untuk Kucing sebagai area istirahat atau hideout kucing, cocok untuk anabul yang suka tempat tidur tertutup/nyaman."
  },
  {
    "hpmSku": "HPM-KM-0033",
    "kmartSku": "P_43553860",
    "name": "Harness & Tali Kucing - Assorted",
    "nameOriginal": "Cat Harness and Lead Set - Assorted",
    "categoryDisplay": "Aksesoris & Harness",
    "categorySlug": "aksesoris-harness",
    "status": "show",
    "price": 225000,
    "priceDisplay": "Rp225,000",
    "productUrl": "https://www.kmart.com.au/product/cat-harness-and-lead-set-assorted-43553860/",
    "imageUrl": "https://assets.kmart.com.au/transform/452c9752-8de0-4316-b4f6-3f6416506df7/43553860-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "harness kucing, tali tuntun kucing, cat harness, lead set, leash kucing, aksesoris jalan kucing",
    "seoPrimaryKeyword": "harness kucing",
    "seoSupportingKeywords": "tali tuntun kucing, leash kucing, cat harness, aksesoris jalan kucing",
    "descriptorShort": "Harness & Tali Kucing - Assorted sebagai aksesoris atau perlengkapan jalan kucing. Pastikan ukuran pas dan nyaman dipakai."
  },
  {
    "hpmSku": "HPM-KM-0034",
    "kmartSku": "P_43287284",
    "name": "Paket 15 Mainan Kucing",
    "nameOriginal": "Cat Toy 15 Pack",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "show",
    "price": 250000,
    "priceDisplay": "Rp250,000",
    "productUrl": "https://www.kmart.com.au/product/cat-toy-15-pack-43287284/",
    "imageUrl": "https://assets.kmart.com.au/transform/c32faf66-4266-4f05-bcd2-639505a99f12/43287284-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "paket mainan kucing, cat toy pack, 15 pack toy, mainan anabul, enrichment, mainan interaktif",
    "seoPrimaryKeyword": "paket mainan kucing",
    "seoSupportingKeywords": "mainan kucing indoor, cat toy pack, mainan enrichment kucing",
    "descriptorShort": "Paket 15 Mainan Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0035",
    "kmartSku": "P_43423774",
    "name": "Play Centre Mainan Kucing",
    "nameOriginal": "Cat Toy Play Centre",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "top_pick",
    "price": 250000,
    "priceDisplay": "Rp250,000",
    "productUrl": "https://www.kmart.com.au/product/cat-toy-play-centre-43423774/",
    "imageUrl": "https://assets.kmart.com.au/transform/e6863c24-41a3-414f-ba75-529848a2fea6/43423774-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "play centre kucing, cat play center, mainan interaktif, enrichment kucing, activity toy, mainan aktif",
    "seoPrimaryKeyword": "mainan interaktif kucing",
    "seoSupportingKeywords": "play centre kucing, cat activity toy, mainan enrichment kucing",
    "descriptorShort": "Play Centre Mainan Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0036",
    "kmartSku": "P_43661794",
    "name": "Bola Scratcher Rolling untuk Kucing",
    "nameOriginal": "Rolling Cat Scratcher Ball - Small",
    "categoryDisplay": "Cat Tree & Scratcher",
    "categorySlug": "cat-tree-scratcher",
    "status": "top_pick",
    "price": 250000,
    "priceDisplay": "Rp250,000",
    "productUrl": "https://www.kmart.com.au/product/rolling-cat-scratcher-ball-small-43661794/",
    "imageUrl": "https://assets.kmart.com.au/transform/046812fc-6386-42a7-a36d-4f696963ea46/43661794-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "rolling scratcher, bola scratcher, garukan kucing, cat scratcher, scratcher ball, mainan garuk",
    "seoPrimaryKeyword": "garukan kucing",
    "seoSupportingKeywords": "rolling scratcher kucing, cat scratcher ball, mainan garuk kucing",
    "descriptorShort": "Bola Scratcher Rolling untuk Kucing untuk kebutuhan garuk dan bermain, cocok dipertimbangkan agar kucing punya area scratching sendiri."
  },
  {
    "hpmSku": "HPM-KM-0037",
    "kmartSku": "P_43715848",
    "name": "Rumah Kucing Novelty",
    "nameOriginal": "Novelty Cat Cave - Assorted",
    "categoryDisplay": "Kasur & Tempat Tidur",
    "categorySlug": "kasur-tempat-tidur",
    "status": "show",
    "price": 375000,
    "priceDisplay": "Rp375,000",
    "productUrl": "https://www.kmart.com.au/product/novelty-cat-cave-assorted-43715848/",
    "imageUrl": "https://assets.kmart.com.au/transform/096d4aeb-e7a1-4053-9d31-7e6a941c7de3/43715848-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "rumah kucing, novelty cat cave, cat house, tempat tidur kucing, hideout kucing, cat cave",
    "seoPrimaryKeyword": "rumah kucing",
    "seoSupportingKeywords": "novelty cat house, cat cave, tempat tidur kucing, hideout kucing",
    "descriptorShort": "Rumah Kucing Novelty sebagai area istirahat atau hideout kucing, cocok untuk anabul yang suka tempat tidur tertutup/nyaman."
  },
  {
    "hpmSku": "HPM-KM-0039",
    "kmartSku": "P_43715251",
    "name": "Mainan Teaser Otomatis untuk Kucing",
    "nameOriginal": "Cat Automated Teaser",
    "categoryDisplay": "Mainan & Enrichment",
    "categorySlug": "mainan-enrichment",
    "status": "top_pick",
    "price": 475000,
    "priceDisplay": "Rp475,000",
    "productUrl": "https://www.kmart.com.au/product/cat-automated-teaser-43715251/",
    "imageUrl": "https://assets.kmart.com.au/transform/04916f68-78e3-4de7-8b47-16e1a6ed417a/43715251-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "mainan otomatis kucing, automated teaser, automatic cat toy, mainan interaktif, cat teaser, enrichment",
    "seoPrimaryKeyword": "mainan otomatis kucing",
    "seoSupportingKeywords": "automatic cat toy, mainan interaktif kucing, cat teaser otomatis",
    "descriptorShort": "Mainan Teaser Otomatis untuk Kucing untuk stimulasi bermain kucing indoor, membantu aktivitas berburu, mengejar, menggigit, atau eksplorasi ringan."
  },
  {
    "hpmSku": "HPM-KM-0040",
    "kmartSku": "P_43719815",
    "name": "Rumah Kucing Novelty",
    "nameOriginal": "Novelty Cat House - Assorted",
    "categoryDisplay": "Cat Tree & Scratcher",
    "categorySlug": "cat-tree-scratcher",
    "status": "top_pick",
    "price": 500000,
    "priceDisplay": "Rp500,000",
    "productUrl": "https://www.kmart.com.au/product/novelty-cat-house-assorted-43719815/",
    "imageUrl": "https://assets.kmart.com.au/transform/387fccc2-9c41-47bb-8705-0b6ea26af974/43719815-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "rumah kucing, novelty cat house, cat scratcher house, rumah scratcher, garukan kucing, hideout kucing",
    "seoPrimaryKeyword": "garukan kucing",
    "seoSupportingKeywords": "novelty cat house, cat scratcher house, rumah scratcher kucing",
    "descriptorShort": "Rumah Kucing Novelty untuk kebutuhan garuk dan bermain, cocok dipertimbangkan agar kucing punya area scratching sendiri."
  },
  {
    "hpmSku": "HPM-KM-0041",
    "kmartSku": "P_42952879",
    "name": "Carrier Lipat untuk Kucing",
    "nameOriginal": "Pet Carrier Foldable",
    "categoryDisplay": "Carrier & Travel",
    "categorySlug": "carrier-travel",
    "status": "top_pick",
    "price": 550000,
    "priceDisplay": "Rp550,000",
    "productUrl": "https://www.kmart.com.au/product/pet-carrier-foldable-42952879/",
    "imageUrl": "https://assets.kmart.com.au/transform/164a1db1-8626-489e-b2e8-dbbd54d4b70c/42952879-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "carrier kucing, pet carrier, tas kucing, kandang travel, carrier lipat, travel anabul",
    "seoPrimaryKeyword": "carrier kucing",
    "seoSupportingKeywords": "pet carrier, tas kucing, carrier lipat, kandang travel kucing",
    "descriptorShort": "Carrier Lipat untuk Kucing untuk kebutuhan bepergian, vet visit, atau perlengkapan mobil bersama anabul. Cek ukuran dan kompatibilitas sebelum beli."
  },
  {
    "hpmSku": "HPM-KM-0042",
    "kmartSku": "P_42302216",
    "name": "Carrier Lipat Kecil untuk Kucing",
    "nameOriginal": "Pet Carrier Foldable - Small",
    "categoryDisplay": "Carrier & Travel",
    "categorySlug": "carrier-travel",
    "status": "show",
    "price": 675000,
    "priceDisplay": "Rp675,000",
    "productUrl": "https://www.kmart.com.au/product/pet-carrier-foldable-small-42302216/",
    "imageUrl": "https://assets.kmart.com.au/transform/5288d051-f164-403e-be38-726f2eb8c45d/42302216-1?io=transform:extend,width:580,height:725",
    "searchKeywords": "carrier kucing kecil, pet carrier small, tas kucing kecil, carrier lipat, kandang travel, travel anabul",
    "seoPrimaryKeyword": "carrier kucing kecil",
    "seoSupportingKeywords": "pet carrier small, tas kucing kecil, carrier lipat kucing",
    "descriptorShort": "Carrier Lipat Kecil untuk Kucing untuk kebutuhan bepergian, vet visit, atau perlengkapan mobil bersama anabul. Cek ukuran dan kompatibilitas sebelum beli."
  }
];

window.HIPAWMATE_PRODUCTS = products;
